/**
 * julIDE design tokens — the single source of truth for the visual system.
 *
 * Everything visual derives from this file: the CSS custom properties in
 * `src/styles/tokens.css` (generated by `bun run generate:tokens`), the Monaco
 * editor themes, and the xterm terminal palettes in `src/themes/themes.ts`.
 *
 * Before this existed, the chrome colors lived in App.css and the editor and
 * terminal palettes were hand-copied hex in separate files, so they drifted
 * apart silently. Nothing should hardcode a color outside this module.
 *
 * ── Direction: "Instrument" ──────────────────────────────────────────────
 * The ground is a cool blue-graphite (Julia's #4063D8 desaturated toward
 * black) rather than VS Code's neutral grey, which the old palette copied
 * verbatim.
 *
 * Accent colors are not decoration: they are Julia's own REPL prompt modes,
 * which every Julia user has already internalized.
 *
 *   julia>   green    running, success, tests passing
 *   pkg>     blue     packages, environments, informational
 *   help?>   yellow   docs, warnings, pending work
 *   shell>   red      errors, failures, destructive actions
 *            purple   identity, selection, focus, debugging
 */

/** A theme's full color surface. Every value is a `#rrggbb` literal. */
export interface Palette {
  /** Backgrounds, from deepest (editor) to most raised (dialogs). */
  surface: {
    canvas: string;
    chrome: string;
    panel: string;
    raised: string;
    hover: string;
    active: string;
    selected: string;
    /**
     * Backing plate for rendered plot output and embedded HTML.
     *
     * Deliberately white in *both* themes: Plots.jl and friends render onto a
     * transparent or white canvas with dark axes and text, so a dark plate
     * makes real figures unreadable. This is a content surface, not chrome.
     */
    plot: string;
  };
  /** 1px dividers. `strong` separates major regions, `default` everything else. */
  hairline: { default: string; strong: string };
  /** Foreground ramp. `inverse` reads against a filled mode color.
   *  Emitted as `--fg-*` so it never collides with the `--text-*` size scale. */
  fg: { hi: string; mid: string; lo: string; inverse: string };
  /** Julia's REPL prompt modes, used semantically throughout the UI. */
  mode: {
    run: string;
    pkg: string;
    help: string;
    shell: string;
    brand: string;
  };
  /** Julia syntax colors for Monaco. Kept separate so code can be tuned for
   *  reading density without dragging the whole UI palette with it. */
  syntax: {
    keyword: string;
    type: string;
    func: string;
    macro: string;
    symbol: string;
    string: string;
    number: string;
    comment: string;
    operator: string;
  };
  /** Elevation. Tinted with the theme's ink rather than pure black — the old
   *  pure-black shadows were unusably heavy in light mode. */
  elevation: { e1: string; e2: string; e3: string };
  /** Backdrop behind modals. */
  scrim: string;
  /** Editor selection and current-line. */
  editor: { selection: string; lineHighlight: string };
}

export const dark: Palette = {
  surface: {
    canvas: "#0e1116",
    chrome: "#131820",
    panel: "#171d27",
    raised: "#1e2530",
    hover: "#232c39",
    active: "#2c3745",
    selected: "#243449",
    plot: "#ffffff",
  },
  hairline: { default: "#202834", strong: "#33404f" },
  fg: { hi: "#dde4ee", mid: "#94a2b4", lo: "#7a8896", inverse: "#0e1116" },
  mode: {
    run: "#3fae3a",
    pkg: "#6c8cf0",
    help: "#e0a93f",
    shell: "#e85c50",
    brand: "#b072d1",
  },
  syntax: {
    keyword: "#b072d1",
    type: "#6c8cf0",
    func: "#8fb8f5",
    macro: "#e85c50",
    symbol: "#e0a93f",
    string: "#6fc26a",
    number: "#4fc1b0",
    comment: "#717f90",
    operator: "#9db0c6",
  },
  elevation: {
    e1: "0 1px 2px rgb(0 0 0 / 0.40), 0 2px 8px rgb(0 0 0 / 0.30)",
    e2: "0 2px 4px rgb(0 0 0 / 0.40), 0 8px 20px rgb(0 0 0 / 0.40)",
    e3: "0 4px 8px rgb(0 0 0 / 0.40), 0 16px 48px rgb(0 0 0 / 0.55)",
  },
  scrim: "rgb(0 0 0 / 0.60)",
  editor: { selection: "#2b4260", lineHighlight: "#161d26" },
};

export const light: Palette = {
  surface: {
    canvas: "#ffffff",
    chrome: "#eef1f6",
    panel: "#f5f7fa",
    raised: "#ffffff",
    hover: "#e4e9f1",
    active: "#d7dee9",
    selected: "#dbe6f7",
    plot: "#ffffff",
  },
  hairline: { default: "#dfe4ec", strong: "#c3ccd9" },
  fg: { hi: "#0e1116", mid: "#4c596b", lo: "#6d7986", inverse: "#ffffff" },
  mode: {
    run: "#2a7d20",
    pkg: "#2d4fa0",
    help: "#8f640a",
    shell: "#c0342a",
    brand: "#7b3f9e",
  },
  syntax: {
    keyword: "#7b3f9e",
    type: "#2d4fa0",
    func: "#3a6bb8",
    macro: "#c0342a",
    symbol: "#96690a",
    string: "#2a7d20",
    number: "#0f7d6e",
    comment: "#68737f",
    operator: "#4c596b",
  },
  elevation: {
    e1: "0 1px 2px rgb(14 17 22 / 0.06), 0 2px 8px rgb(14 17 22 / 0.06)",
    e2: "0 2px 4px rgb(14 17 22 / 0.08), 0 8px 20px rgb(14 17 22 / 0.10)",
    e3: "0 4px 8px rgb(14 17 22 / 0.10), 0 16px 48px rgb(14 17 22 / 0.16)",
  },
  scrim: "rgb(14 17 22 / 0.35)",
  editor: { selection: "#cddffa", lineHighlight: "#f3f6fa" },
};

export const palettes = { dark, light } as const;
export type PaletteName = keyof typeof palettes;

/* ─────────────────────────────────────────────────────────────────────────
   Scales — theme-independent
   ───────────────────────────────────────────────────────────────────────── */

/**
 * 4px base with two half-steps. 6px is kept deliberately: `gap: 6px` appears
 * 30 times in the pre-redesign stylesheet and it is a legitimate half-step for
 * icon-to-label spacing at this density.
 */
export const space = {
  1: "2px",
  2: "4px",
  3: "6px",
  4: "8px",
  5: "12px",
  6: "16px",
  7: "24px",
  8: "32px",
} as const;

/** Collapses the old interchangeable 3px/4px pair into one small radius. */
export const radius = {
  xs: "2px",
  sm: "4px",
  md: "6px",
  lg: "10px",
  full: "999px",
} as const;

/**
 * Type scale. `2xs` and `xs` are set in IBM Plex Sans Condensed — condensed
 * type is what makes it affordable to put readable text labels on the
 * activity bar and status bar instead of bare icons.
 */
export const type = {
  "2xs": { size: "10px", line: "14px" },
  xs: { size: "11px", line: "16px" },
  sm: { size: "12px", line: "18px" },
  base: { size: "13px", line: "20px" },
  md: { size: "15px", line: "22px" },
  lg: { size: "19px", line: "26px" },
  xl: { size: "28px", line: "34px" },
} as const;

export const fontStack = {
  ui: '"IBM Plex Sans", system-ui, -apple-system, "Segoe UI", Roboto, sans-serif',
  condensed: '"IBM Plex Sans Condensed", "IBM Plex Sans", system-ui, sans-serif',
  // JetBrains Mono is bundled (see src/styles/fonts.css). It is the code font
  // rather than IBM Plex Mono because Plex Mono has no Greek coverage, and
  // Julia identifiers routinely use α, β, θ and friends.
  mono: '"JetBrains Mono", "Fira Code", "Cascadia Code", "Noto Sans Mono", Consolas, monospace',
} as const;

/** Only three weights. The old stylesheet mixed 300/400/500/600/700/bold. */
export const weight = { regular: "400", medium: "500", semibold: "600" } as const;

export const motion = {
  duration: { 1: "120ms", 2: "180ms", 3: "240ms" },
  ease: {
    out: "cubic-bezier(0.2, 0.8, 0.3, 1)",
    inOut: "cubic-bezier(0.4, 0, 0.2, 1)",
  },
} as const;

/** Replaces eight ad-hoc lucide `size=` values. */
export const iconSize = { xs: 12, sm: 14, md: 16, lg: 20 } as const;

export const zIndex = {
  sticky: 10,
  dropdown: 100,
  popover: 200,
  scrim: 300,
  modal: 310,
  toast: 400,
} as const;

/** Fixed chrome heights. */
export const layout = {
  toolbarHeight: "40px",
  statusbarHeight: "24px",
  tabsHeight: "35px",
  panelTabsHeight: "30px",
  activityBarWidth: "56px",
  activityBarCompactWidth: "48px",
} as const;

/* ─────────────────────────────────────────────────────────────────────────
   Helpers
   ───────────────────────────────────────────────────────────────────────── */

/**
 * `#rrggbb` → `"r g b"` space-separated channels.
 *
 * Tints are composed as `rgb(var(--mode-run-rgb) / 0.16)` rather than with
 * `color-mix()`, which is not safe on the older WKWebView builds Tauri may run
 * against on macOS.
 */
export function hexToChannels(hex: string): string {
  const h = hex.replace("#", "");
  const n = parseInt(
    h.length === 3
      ? h
          .split("")
          .map((c) => c + c)
          .join("")
      : h,
    16,
  );
  return `${(n >> 16) & 255} ${(n >> 8) & 255} ${n & 255}`;
}

/** Monaco wants `rrggbb` with no leading `#` in its token rules. */
export function bare(hex: string): string {
  return hex.replace("#", "");
}

/** Blend two `#rrggbb` colors. `ratio` is how far to move from `a` toward `b`. */
export function mix(a: string, b: string, ratio: number): string {
  const channels = (hex: string) => hexToChannels(hex).split(" ").map(Number);
  const [r1, g1, b1] = channels(a);
  const [r2, g2, b2] = channels(b);
  return (
    "#" +
    [
      Math.round(r1 + (r2 - r1) * ratio),
      Math.round(g1 + (g2 - g1) * ratio),
      Math.round(b1 + (b2 - b1) * ratio),
    ]
      .map((v) => v.toString(16).padStart(2, "0"))
      .join("")
  );
}

/** Interactive hover for a mode color: lift toward white on dark, deepen on light. */
export function hoverOf(hex: string, isDark: boolean): string {
  return isDark ? mix(hex, "#ffffff", 0.16) : mix(hex, "#000000", 0.14);
}
