#!/usr/bin/env bun
/**
 * Bundles src/plugin-sdk/bootstrap.ts to src-tauri/assets/plugin-bootstrap.js.
 *
 * Rust `include_str!`s the output and inlines it into every sandboxed plugin frame, so
 * a stale build means plugins run against an old SDK with no sign that anything is
 * wrong. `scripts/check-plugin-bootstrap.ts` re-runs this and fails if the checked-in
 * file has drifted, so CI catches an edit to bootstrap.ts that was never rebuilt.
 *
 * Not a Vite entry point: keeping it a standalone Bun build leaves vite.config.ts alone
 * and means `cargo build` does not depend on the frontend build having run first.
 *
 * Usage:  bun run build:plugin-bootstrap
 */

const ENTRY = "src/plugin-sdk/bootstrap.ts";
const OUT = "src-tauri/assets/plugin-bootstrap.js";

const HEADER = `// GENERATED by scripts/build-plugin-bootstrap.ts from src/plugin-sdk/bootstrap.ts.
// Do not edit. Run: bun run build:plugin-bootstrap
`;

export async function render(): Promise<string> {
  const result = await Bun.build({
    entrypoints: [ENTRY],
    target: "browser",
    // IIFE, not ESM: this is inlined into a classic <script> so it can run before the
    // plugin's own module and set up the global the module assigns its exports to.
    format: "iife",
    minify: false,
    sourcemap: "none",
  });

  if (!result.success) {
    const messages = result.logs.map((l) => String(l)).join("\n");
    throw new Error(`Failed to bundle ${ENTRY}:\n${messages}`);
  }
  const [artifact] = result.outputs;
  if (!artifact) throw new Error(`${ENTRY} produced no output`);

  const code = await artifact.text();

  // The bundle is inlined into HTML by src-tauri/src/plugin_protocol.rs, which escapes
  // `</script`. Failing here as well makes the invariant visible at build time rather
  // than only at serve time.
  if (code.includes("</script")) {
    throw new Error(
      "The bundled bootstrap contains `</script`, which must be escaped before inlining.",
    );
  }

  return HEADER + code;
}

if (import.meta.main) {
  await Bun.write(OUT, await render());
  console.log(`Wrote ${OUT}`);
}
